import { Chart, Table, Kpis } from '../components';
import { Row, number } from '../api';
import type { Data } from 'plotly.js';

export type PageData = {overview:Record<string,number>;trend:Row[];regions:Row[];categories:Row[];products:Row[];rfm:Row[];promotions:Row[];anomalies:Row[];
 segments:{status:string;selected_k:number;silhouette:number;profiles:Row[];customers:Row[];evaluation:Row[]};
 forecast:{status:string;selected_model:string;history:Row[];future:Row[];holdout:Row[];baseline_metrics:Row;xgboost_metrics:Row;caveat:string}};
const values=(rows:Row[],key:string)=>rows.map(row=>row[key]) as number[];
const bar=(rows:Row[],x:string,y:string):Data=>({type:'bar',x:values(rows,x),y:values(rows,y),hovertemplate:'%{x}<br>%{y:,.2f}<extra></extra>',marker:{color:'#277d69'}});
const line=(rows:Row[],key:string,name:string):Data=>({type:'scatter',mode:'lines+markers',name,x:values(rows,'date'),y:values(rows,key),line:{width:2.5},marker:{size:4},hovertemplate:'%{x|%b %Y}<br>%{y:,.2f}<extra>'+name+'</extra>'});

export default function Analytics({page,data}:{page:string;data:Partial<PageData>}){
 const {overview={},trend=[],regions=[],categories=[],products=[],rfm=[],promotions=[],anomalies=[],segments,forecast}=data;
 if(page==='Overview'||page==='Sales Analytics')return <>
  <Kpis data={overview}/><div className="chart-grid wide"><Chart title="Revenue & profit over time" subtitle="Monthly Â· INR" data={[line(trend,'revenue','Revenue'),line(trend,'profit','Profit')]}/><Chart title="Regional contribution" subtitle="Revenue Â· INR" data={[bar(regions,'region','revenue')]}/></div>
  <div className="chart-grid"><Chart title="Category performance" subtitle="Revenue Â· INR" data={[bar(categories,'category','revenue')]}/><section className="panel insight"><span className="eyebrow">THE SELECTED PERIOD</span><h3>A closer look at your business</h3><div><strong>{number(overview.orders||0)}</strong><span>distinct orders</span></div><div><strong>{number(overview.customers||0)}</strong><span>purchasing customers</span></div><div><strong>{number(overview.repeat_purchase_pct||0)}%</strong><span>customers with more than one order</span></div><p>Explore products and promotions to understand where revenue and margin differ.</p></section></div>
  <Table title={page==='Overview'?'Product leaderboard':'Monthly performance'} rows={page==='Overview'?products:trend} columns={page==='Overview'?['product_name','category','revenue','profit','margin_pct','health_score','health']:['date','revenue','profit','quantity','mom_pct','yoy_pct']}/>
 </>;
 if(page==='Consumer Intelligence'){
  const counts=Object.entries(rfm.reduce<Record<string,number>>((all,row)=>{const key=String(row.segment);all[key]=(all[key]||0)+1;return all},{}));
  return <><div className="notice">RFM is relative to the latest selected transaction. Frequency counts distinct orders. Clusters describe observed behavior; they are not causal or demographic groups.</div><div className="chart-grid"><Chart title="Customer segments" subtitle="Rule-based RFM" data={[{type:'pie',labels:counts.map(v=>v[0]),values:counts.map(v=>v[1]),hole:.62,textinfo:'percent',hoverinfo:'label+value'}]}/><Chart title="Customer value & recency" subtitle="Each point is a customer" data={[{type:'scatter',mode:'markers',x:values(rfm,'recency'),y:values(rfm,'monetary'),text:values(rfm,'customer_id') as unknown as string[],marker:{size:7,opacity:.6,color:'#277d69'},hovertemplate:'%{text}<br>%{x} days<br>INR %{y:,.0f}<extra></extra>'}]} layout={{xaxis:{title:{text:'Recency (days)'}},yaxis:{title:{text:'Customer revenue (INR)'}}}}/></div>
  {segments?.status==='ok'?<><div className="section-heading"><h3>K-Means Â· {segments.selected_k} clusters</h3><span>Silhouette {segments.silhouette.toFixed(3)}</span></div><Table title="Cluster profiles Â· mean RFM values" rows={segments.profiles}/><Chart title="Cluster-count evaluation" subtitle="Higher silhouette indicates better separation" data={[bar(segments.evaluation,'k','silhouette')]}/></>:<p>Insufficient customer variation for clustering.</p>}<Table title="Customer RFM" rows={rfm}/></>;
 }
 if(page==='Product Intelligence')return <><div className="notice">Health combines growth (25%), margin (30%), volume (15%), customer demand (15%) and consistency (15%). Missing growth receives a neutral component.</div><div className="chart-grid"><Chart title="Revenue versus profitability" subtitle="Product performance matrix" data={[{type:'scatter',mode:'text+markers',x:values(products,'revenue'),y:values(products,'margin_pct'),text:values(products,'product_name') as unknown as string[],textposition:'top center',marker:{size:12,color:values(products,'health_score'),colorscale:'Greens',showscale:true},hovertemplate:'%{text}<br>INR %{x:,.0f}<br>Margin %{y:.1f}%<extra></extra>'}]} layout={{xaxis:{title:{text:'Revenue (INR)'}},yaxis:{title:{text:'Margin (%)'}}}}/><Chart title="Product health" subtitle="Transparent score Â· 0â€“100" data={[bar(products,'product_name','health_score')]}/></div><Table title="SKU performance" rows={products} columns={['product_name','revenue','profit','growth_pct','margin_pct','discount_revenue_share_pct','health_score','health']}/></>;
 if(page==='Promotions')return <><div className="notice">Discounts are associated with these outcomes. Differences in products, timing and customers prevent causal conclusions. Units per line do not measure campaign lift.</div><div className="chart-grid"><Chart title="Discount & basket quantity" subtitle="Mean units per transaction line" data={[{type:'scatter',mode:'markers',x:values(promotions,'discount').map(v=>v*100),y:values(promotions,'units_per_line'),marker:{size:18,color:'#277d69'}}]} layout={{xaxis:{title:{text:'Discount (%)'}},yaxis:{title:{text:'Units per line'}}}}/><Chart title="Campaign profitability" subtitle="Gross profit Â· INR" data={[bar(promotions,'campaign','profit')]}/></div><Table title="Promotion performance" rows={promotions}/></>;
 if(page==='Forecasting')return forecast?.status==='ok'?<><div className="notice">Selected model: <b>{forecast.selected_model}</b>. Chronological recursive holdout; XGBoost must improve MAE by at least 2%. Forecasts are weekly units.</div><Chart title="Demand outlook" subtitle="Four complete weeks ahead" data={[line(forecast.history,'actual','Observed'),{...line(forecast.future,'predicted','Forecast'),line:{dash:'dash',width:3,color:'#dba54b'}}]}/><div className="chart-grid"><Chart title="Holdout evaluation" subtitle="Actual vs recursive predictions Â· units" data={[line(forecast.holdout,'actual','Actual'),line(forecast.holdout,'baseline','Baseline'),line(forecast.holdout,'xgboost','XGBoost')]}/><Table title="Measured model performance" rows={[{model:'Moving average',...forecast.baseline_metrics},{model:'XGBoost',...forecast.xgboost_metrics}]}/></div><p className="footnote">{forecast.caveat}</p></>:<div className="empty panel">At least 48 complete weeks are required. Broaden the date range.</div>;
 if(page==='Anomaly Monitor')return <><div className="notice">Unsupervised review candidates. Alerts require an Isolation Forest signal, at least 3 standard deviations and a 25% deviation from the trailing eight-week median. No ground-truth labels are available.</div><Chart title="Flagged sales observations" subtitle="Weekly revenue Â· INR" data={[{type:'scatter',mode:'markers',x:values(anomalies,'date'),y:values(anomalies,'observed'),text:values(anomalies,'entity') as unknown as string[],marker:{size:12,color:'#b87149'},name:'Observed',hovertemplate:'%{text}<br>%{x}<br>INR %{y:,.0f}<extra></extra>'},{type:'scatter',mode:'markers',x:values(anomalies,'date'),y:values(anomalies,'expected'),name:'Trailing median',marker:{symbol:'x',size:10,color:'#277d69'}}]}/><Table title="Investigate these signals" rows={anomalies}/></>;
 return null;
}

