import { useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { Filters } from '../api';
type Answer={answer:string;recommendation:string;key_metrics:Record<string,number>;supporting_evidence:unknown;caveats:string[];mode:string};
export default function Copilot({filters}:{filters:Filters}){
 const [question,setQuestion]=useState('');const [answer,setAnswer]=useState<Answer|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const examples=['What happened to revenue last month?','Which products are declining?','Compare Maharashtra and Gujarat sales in Q2 2025','Which customers are most valuable?'];
 async function ask(text:string){setQuestion(text);setBusy(true);setError('');setAnswer(null);try{const response=await fetch('/api/copilot/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:text,filters:Object.fromEntries(Object.entries(filters).filter(([,v])=>v))}),signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error('Copilot is unavailable. Check the analytics service and try again.');setAnswer(await response.json())}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 return <div className="copilot"><span className="eyebrow">RETAILIQ COPILOT</span><h2>Start with a business question.</h2><p>Explore your data with a controlled analytical operation. Every numerical answer is computed from the selected transactions.</p><div className="suggestions">{examples.map(text=><button key={text} disabled={busy} onClick={()=>void ask(text)}>{text}<ArrowUpRight size={17}/></button>)}</div><form onSubmit={event=>{event.preventDefault();void ask(question)}}><label htmlFor="question">Your question</label><div className="ask"><input id="question" required minLength={3} maxLength={1000} value={question} onChange={event=>setQuestion(event.target.value)} placeholder="Ask about revenue, products, customers or demand…"/><button disabled={busy}>{busy?'Analyzing…':'Analyze'}</button></div></form>{error&&<div role="alert" className="error">{error}</div>}{answer&&<article className="panel answer"><span className="eyebrow">{answer.mode}</span><h3>{answer.answer}</h3><h4>Recommended next step</h4><p>{answer.recommendation}</p><details open><summary>Supporting evidence</summary><pre>{JSON.stringify(answer.supporting_evidence,null,2)}</pre></details><h4>Interpretation notes</h4><ul>{answer.caveats.map((c,i)=><li key={i}>{c}</li>)}</ul></article>}</div>
}
